### ISSUE TITLE
Application hangs when closing

### ISSUE THREAD

**Issue by jjvliu** [bkacjios/m-overlay#169]
**Describe the bug**
Opening then shortly closing M'Overlay 2.1.1 without even opening Slippi sometimes causes M'Overlay to hang. This happens to me roughly 150 out of 200 times with no clear pattern. When M'Overlay hangs, it can be properly closed by closing the debug popup window.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Dolphin Version: n/a

**To Reproduce**
1. Open M'Overlay in debugging mode.
2. (Optional) Interact with the UI by clicking around and/or pressing escape.
3. Click the X to close M'Overlay. This will often cause it to stop responding.
4. If M'Overlay stops responding, click the X on the debug console to properly close the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/1088735/225218551-26240b5c-92a6-4413-8065-262f853bd13e.png)
![image](https://user-images.githubusercontent.com/1088735/225218614-2592b049-6443-4015-9f47-570f48614730.png)

**Debug console output**
```
[DEBUG - 22:47:41] M'Overlay (2.1.1)
[DEBUG - 22:47:41] Love2D 11.4.0 - Mysterious Mysteries
[DEBUG - 22:47:41] Lua 5.1 (LuaJIT 2.1.0-beta3 - x64)
[DEBUG - 22:47:41] System: Windows
[DEBUG - 22:47:41] Renderer: OpenGL (3.3.14831 Core Profile Context 21.10.03.11 27.20.21003.11000)
[DEBUG - 22:47:41] Graphics: ATI Technologies Inc. (Radeon RX Vega M GH Graphics)
```
**Additional context**
Possibly related to #164 but I thought I would record this very minimal working example. I also **cannot** reproduce the bug on the debug build 2.1.0-2-g0d95481 from this comment:
https://github.com/bkacjios/m-overlay/issues/164#issuecomment-1461112812_

**Comment by bkacjios** [comment]
This is another thing I can't reproduce. I closed and reopened the application at least 50 times without a single crash.
I do have a hunch that it's getting stuck shutting down the thread that handles updating the application for some reason.

**Comment by bkacjios** [comment]
I pushed out a new update to hopefully fix your crash on close issue.

**Comment by jjvliu** [comment]
Today I confirmed my issue persists on 2.1.1a. I also still saw #164 on 2.1.1 but have not tested it on 2.1.1a.
