### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by CaptainManlove** [bkacjios/m-overlay#80]
M'Overlay has been crashing at random while playing slippi and turning itself off. Not simply ceasing to play music but fully closing. This seems to happen most often during during any quick series of changes in screen. ie when someone quickly quits/disconnects out of a match the second it loads. But it also happened a few times just in the character select menu when I hit B too many times, despite b currently not doing anything as my character was selected and I was looking for a game.
Also after it has crashed it will cease to function again unless I turn off Slippi, then turn M'Overlay back on. Turning M'Overlay back on immediately will simply cause another crash.

**Desktop (please complete the following information):**
 - OS: Windows
 - Dolphin Version: Slippi 2.2.6

**To Reproduce**
1. Turn on m'overlay, 
2. Turn on slippi, 
3. Go to quickmatch and...
4. Either: have a screen swap quickly, press a button too many times, or just play some matches and eventually the m'overlay client will crash.

**Expected behavior**
The m'overlay client will not cease functioning until it is turned off.

**Screenshots**
None applicable

**Debug console output**
```
[INFO  - 19:05:06] [DOLPHIN] Hooked
[INFO  - 19:05:06] [DOLPHIN] Watching ram: 7FFF0000 [2000000]
[DEBUG - 19:05:06] [DOLPHIN] Game: GALE01 revision 2
[INFO  - 19:05:06] [DOLPHIN] Loaded game config: GALE01-2
[INFO  - 19:05:06] [MEMORY] Mapping game memory..
[DEBUG - 19:05:06] [MEMORY] [0x8046B6AE  = 0x00000001] match.finished = true
[DEBUG - 19:05:07] [MEMORY] [0x80453130 -> 0xFFFFFFFF80D0E660] player.1.entity -> 0xFFFFFFFF80D0E660
[DEBUG - 19:05:07] [MEMORY] [0x80479D30  = 0x00000008] menu.major = 8
[DEBUG - 19:05:07] [MEMORY] [0x8046B6A5  = 0x00000000] match.playing = false
[DEBUG - 19:05:07] [MEMORY] [0x8049E753  = 0x0000001C] stage = 28
[DEBUG - 19:05:07] [MEMORY] [0x804A0BC0 -> 0xFFFFFFFF8111F920] player.1.cursor -> 0xFFFFFFFF8111F920
[DEBUG - 19:05:07] [MEMORY] [0x80453FC0 -> 0xFFFFFFFF80D4E860] player.2.entity -> 0xFFFFFFFF80D4E860
[DEBUG - 19:05:07] [MEMORY] [0x8046B6A8  = 0x00000002] match.result = 2
[DEBUG - 19:05:07] [MEMORY] [0x80005614 -> 0xFFFFFFFF811135C0] slippi -> 0xFFFFFFFF811135C0
[DEBUG - 19:05:07] [MEMORY] [0xFFFFFFFF811135C0 -> 0xFFFFFFFF81113600] slippi -> 0xFFFFFFFF81113600
[DEBUG - 19:05:07] [MEMORY] [0xFFFFFFFF81113603  = 0x00000001] slippi.local_player.index = 1
[DEBUG - 19:05:07] [MUSIC] Loaded 5 songs in "Melee/Menu Music"
[DEBUG - 19:05:07] [AUTOPORT] Forcing port 1 in menus
[INFO  - 19:05:07] [MUSIC] Playing track #1 for menu
[INFO  - 19:05:07] [MUSIC] Playing track #2 for menu

Then it crashes.

```
**Additional context**
I actually think I may have fixed this myself just by meddling, but if anyone else still has this problem I'll leave this here so they can see it.

Inside of my menu music folder was another folder named "Menu" that had menu 2 music in it from when I originally downloaded songs from the first reddit post about fixing slippis music problem with m'overlay. But all the other menu music options I had were in the menu music folder proper. It seems that every time the die was rolled and that m'overlay tried to interact with that extra layer of folder it just crashed? I'm not sure if this was the case but I haven't been able to reproduce this bug since removing the erroneous folder. 

This explanation doesn't seem to account for every possible circumstance under which the client would seem to crash, but if it happens again after this file change I'll have the debug info ready.

Edit*
Nevermind, the problem persists and here is the crash report.

**Comment by bkacjios** [comment]
I've noticed this too, and from what I can tell it seemed to happen when printing to the debug console. Like the best way I could get it to crash was enabling/disabling the debug console and getting it to print something. 

It's strange though, I haven't been able to get it to crash again today.

**Comment by CaptainManlove** [comment]
Mine crashes regardless of debug being up.

**Comment by bkacjios** [comment]
I think I narrowed down the crashes to the console. I could get a 100% crash if you ever disabled the console.

https://github.com/bkacjios/m-overlay/releases/tag/v1.7.2-RC

Let me know if this beta build fixes it for you.

**Comment by Carldacious** [comment]
I experienced some crashes when playing with the GC Adapter last night, but this build (1.7.2-RC) seems to have fixed it for me!

What is strange is that before last night I had no issues with using the GC Adapter. I don't imagine the problem could be related to a date.

**Comment by bkacjios** [comment]
Yeah, it's very strange. The worst part is that M'Overlay is programmed in a scripting language, so when it crashes, it's usually because of the underlying API. I think a windows update changed something in the windows kernel which started to cause it to crash. All I did was mess around and change the debug console code to no longer allocate/destroy itself depending on if it's enabled or disabled. Now it only allocates it once and hides/shows itself depending on the checkbox.

I'm going to leave this issue open for another day or so to see if anyone gets another random crash before I consider this resolved.

**Comment by Carldacious** [comment]
Ah that makes sense. Great work as always! I will update if I encounter anything weird! Thanks again!

**Comment by SheeshFr** [comment]
I'm still getting crashes on the new build. Does the console log get recorded anywhere? If so, I can send that over.

I've noticed the crashes happen most when in the CSS screen or between/beginning matches (when using it for Melee.) The CSS crashes occur usually a couple seconds in after returning from a match. The other most common crash is right after the Slippi VS screen; when I load into a level, no music plays despite having audio in the CSS.

Thanks for making this software!

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-237).zip](https://github.com/bkacjios/m-overlay/files/6273893/m-overlay-x64.master-237.zip)

Here's a build that will log all output to a file. The log files will be in the config directory. You can open this directory by hitting escape and pressing `open config directory`

**Comment by LysitheaDarkKnight** [comment]
I'm also having crashes that occur in-between games on the CCS when playing online. When I reopen, it immediately crashes again so I have to open during VS screen or the match.

Sometimes, it'll even crash my dolphin when opening it. I've been having this problem since around last month or so.

Crashes are less common compared to before in the latest version, but still an issue. Thanks though for making this software, been really liking it for music in Melee!

**Comment by bkacjios** [comment]
Has anyone tried using an older build to see if the crashes still happen?

**Comment by LysitheaDarkKnight** [comment]
Used v1.6.1 for an hour and it didn't crash once. But I think I need to use it more to fully confirm.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-238).zip](https://github.com/bkacjios/m-overlay/files/6274760/m-overlay-x64.master-238.zip)

Here's another beta build. I compiled Love2d myself with a updated LuaJit library. Also did some more optimizations. I'm really at a loss here. I haven't been able to get it to crash, but I don't know if it's actually fixed or not.

**Comment by SheeshFr** [comment]
[INFO  - 16:56:58] [MUSIC] Playing track #3 for stage "Dream Land N64"
[DEBUG - 16:56:58] [MEMORY] [0x80453130 -> 0xFFFFFFFF80D0E660] player.1.entity -> 0xFFFFFFFF80D0E660
[DEBUG - 16:56:58] [MEMORY] [0x80453FC0 -> 0xFFFFFFFF80D517A0] player.2.entity -> 0xFFFFFFFF80D517A0
[DEBUG - 16:57:00] [MEMORY] [0x8046B6A5  = 0x00000001] match.playing = true
[DEBUG - 17:00:07] [MEMORY] [0x8046B6A5  = 0x00000000] match.playing = false
[DEBUG - 17:00:07] [MEMORY] [0x8046B6A8  = 0x00000002] match.result = 2
[DEBUG - 17:00:09] [MEMORY] [0x8046B6AE  = 0x00000001] match.finished = true
[DEBUG - 17:00:09] [MEMORY] [0x80479D33  = 0x00000000] menu.minor = 0
[DEBUG - 17:00:09] [AUTOPORT] Forcing port 1 in menus
[INFO  - 17:00:09] [MUSIC] Playing track #9 for menu
[INFO  - 17:00:09] [MUSIC] Playing track #10 for menu

**Comment by SheeshFr** [comment]
^Last several lines before a crash. I played for about 40min. on direct before this one happened. Going to download v.238 and report any findings with it or (hopefully) play for a good long while and report a full success!

**Comment by bkacjios** [comment]
Okay, I finally can get it to crash consistantly. I played an online match and now it's crashing every time I launch. Currently building a debug build of love2d and will hopefully get a stack trace to figure out what's going on.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-238).zip](https://github.com/bkacjios/m-overlay/files/6274943/m-overlay-x64.master-238.zip)

So here's yet another build. From what I can tell the application is crashing when performing garbage collection.. I managed to scope out some code that when commented out stopped my crash I was experiencing.

**Comment by SheeshFr** [comment]
Nice work! I'll try this build out right now :D

**Comment by bkacjios** [comment]
That's good. I made another RC build to disable the file logging.

**Comment by bkacjios** [comment]
Going to close this now.

https://github.com/bkacjios/m-overlay/releases/tag/v1.7.2

Feel free to reopen or make a new issue if you ever experience a crash again.

**Comment by MrDexia** [comment]
I dont know if this problem persist yet, but in my case te problem was the custom textures, I uncheck load custom textures and the crashes stoped.

**Comment by bkacjios** [comment]
What custom textures? My app doesn't have any option like that.

**Comment by Carldacious** [comment]
I believe they are referencing this option in Dolphin. I am not sure why it would impact m-overlay. 

It's possible might have to do with their system's memory/processing power?

**Comment by bkacjios** [comment]
@nom2king501 I pushed out a fix for that. Looks like you played against someone that must of had a weird name or something.

**Comment by nom2king501** [comment]
> [@nom2king501](https://github.com/nom2king501) I pushed out a fix for that. Looks like you played against someone that must of had a weird name or something.

I saw this message just now wdym "Looks like I played against someone that most of had a weird name or something?

**Comment by nom2king501** [comment]
**Because I still having issue with my M'overlay experience keeps crashing in my end and I have no clue why I try do some other version other lastest M'overlay's, Still keeps happening :(**

**Comment by bkacjios** [comment]
Can you post the crash log?

**Comment by nom2king501** [comment]
yea I can hold on

**Comment by nom2king501** [comment]
This error keep crashing ever time I download it the latest version of M'overlay I try anything in my end :(

![Image](https://github.com/user-attachments/assets/08ca139e-cb2b-4000-ab3b-6ca4ddb839a4)

**Comment by bkacjios** [comment]
Oh, so it's an installer error. Quick google search says that's a permission error. I don't know what's up with that. Either your Windows OS is corrupt or you're on some locked down user account. Maybe try installing it as Administrator? You can always use the portable version if the installer doesn't work.
